import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import QueryProviderCL from "../providers/QueryProvider";
import { CustomToastProvider } from "@/context/toastContext";
import { DialogProvider } from "@/context/dialogsEmpresasProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomToastProvider>
          <QueryProviderCL>
            <DialogProvider>
              {children}
            </DialogProvider>
          </QueryProviderCL>
        </CustomToastProvider>
      </body>
    </html>
  );
}
